/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kingsman.upair;

/**
 *
 * @author admin
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form PassengerRegistrationFrame
     */
    public Registration() {
        initComponents();
        setLocationRelativeTo(null);
        
        idTypeField.removeAllItems();
        String[] idTypes = {
            "Select ID Type", "Driver's License", "Passport", "SSS ID", "UMID", "PhilHealth ID",
            "Voter's ID", "Senior Citizen ID", "Student ID", "Others"
        };
        for (String type : idTypes) {
            idTypeField.addItem(type);
        }
        
        provinceField.addActionListener(e -> {
            String prov = (String) provinceField.getSelectedItem();
            cityField.removeAllItems();
            barangayField.removeAllItems();
            cityField.addItem("Select City/Municipality");
            barangayField.addItem("Select Barangay");

            if (prov == null || prov.contains("Select")) return;

            loadCities(prov);
        });

        cityField.addActionListener(e -> {
            String city = (String) cityField.getSelectedItem();
            barangayField.removeAllItems();
            barangayField.addItem("Select Barangay");

            if (city == null || city.contains("Select")) return;

            loadBarangays(city);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lastNameLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        contactNumberLabel = new javax.swing.JLabel();
        provinceLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        idNumberLabel = new javax.swing.JLabel();
        barangayLabel = new javax.swing.JLabel();
        postalCodeLabel = new javax.swing.JLabel();
        confirmPasswordLabel = new javax.swing.JLabel();
        idTypeLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        contactNumberField = new javax.swing.JTextField();
        idNumberField = new javax.swing.JTextField();
        idTypeField = new javax.swing.JComboBox<>();
        provinceField = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        cityField = new javax.swing.JComboBox<>();
        barangayField = new javax.swing.JComboBox<>();
        postalCodeField = new javax.swing.JTextField();
        confirmPasswordField = new javax.swing.JPasswordField();
        passwordField = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        passengerRegistrationFrame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UPAir");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lastNameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(5, 20, 42));
        lastNameLabel.setText("Last Name:");
        getContentPane().add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        firstNameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(5, 20, 42));
        firstNameLabel.setText("First Name:");
        getContentPane().add(firstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, -1));

        userNameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(5, 20, 42));
        userNameLabel.setText("Username:");
        getContentPane().add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        contactNumberLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contactNumberLabel.setForeground(new java.awt.Color(5, 20, 42));
        contactNumberLabel.setText("Contact Number:");
        getContentPane().add(contactNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, -1, -1));

        provinceLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        provinceLabel.setForeground(new java.awt.Color(5, 20, 42));
        provinceLabel.setText("Province:");
        getContentPane().add(provinceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        cityLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cityLabel.setForeground(new java.awt.Color(5, 20, 42));
        cityLabel.setText("City/Municipality");
        getContentPane().add(cityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, -1, -1));

        idNumberLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        idNumberLabel.setForeground(new java.awt.Color(5, 20, 42));
        idNumberLabel.setText("ID Number");
        getContentPane().add(idNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, -1, -1));

        barangayLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        barangayLabel.setForeground(new java.awt.Color(5, 20, 42));
        barangayLabel.setText("Barangay");
        getContentPane().add(barangayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, -1, -1));

        postalCodeLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        postalCodeLabel.setForeground(new java.awt.Color(5, 20, 42));
        postalCodeLabel.setText("Postal Code");
        getContentPane().add(postalCodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, -1, -1));

        confirmPasswordLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        confirmPasswordLabel.setForeground(new java.awt.Color(5, 20, 42));
        confirmPasswordLabel.setText("Confirm Password");
        getContentPane().add(confirmPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, -1, -1));

        idTypeLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        idTypeLabel.setForeground(new java.awt.Color(5, 20, 42));
        idTypeLabel.setText("ID Type");
        getContentPane().add(idTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(5, 20, 42));
        passwordLabel.setText("Password");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, -1, -1));

        lastNameField.setBackground(new java.awt.Color(255, 255, 255));
        lastNameField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lastNameField.setForeground(new java.awt.Color(5, 20, 42));
        lastNameField.setText("e.g Dela Cruz");
        lastNameField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0)));
        lastNameField.setPreferredSize(new java.awt.Dimension(75, 30));
        getContentPane().add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 200, 35));

        firstNameField.setBackground(new java.awt.Color(255, 255, 255));
        firstNameField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        firstNameField.setForeground(new java.awt.Color(5, 20, 42));
        firstNameField.setText("e.g Juan");
        firstNameField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0)));
        firstNameField.setPreferredSize(new java.awt.Dimension(75, 30));
        getContentPane().add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 200, 35));

        usernameField.setBackground(new java.awt.Color(255, 255, 255));
        usernameField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        usernameField.setForeground(new java.awt.Color(5, 20, 42));
        usernameField.setText("e.g Juan23");
        usernameField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0)));
        usernameField.setPreferredSize(new java.awt.Dimension(75, 30));
        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 200, 35));

        contactNumberField.setBackground(new java.awt.Color(255, 255, 255));
        contactNumberField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        contactNumberField.setForeground(new java.awt.Color(5, 20, 42));
        contactNumberField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0)));
        contactNumberField.setPreferredSize(new java.awt.Dimension(75, 30));
        getContentPane().add(contactNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 200, 35));

        idNumberField.setBackground(new java.awt.Color(255, 255, 255));
        idNumberField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        idNumberField.setForeground(new java.awt.Color(5, 20, 42));
        idNumberField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0)));
        idNumberField.setPreferredSize(new java.awt.Dimension(75, 30));
        getContentPane().add(idNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 200, 35));

        idTypeField.setBackground(new java.awt.Color(255, 255, 255));
        idTypeField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        idTypeField.setForeground(new java.awt.Color(5, 20, 42));
        idTypeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select  ID Type", " " }));
        idTypeField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(idTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 200, 35));

        provinceField.setBackground(new java.awt.Color(255, 255, 255));
        provinceField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        provinceField.setForeground(new java.awt.Color(5, 18, 74));
        provinceField.setMaximumRowCount(6);
        provinceField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Province", "Albay", "Camarines Sur", "Camarines Norte", "Catanduanes", "Masbate", "Sorsogon" }));
        provinceField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(provinceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 200, 35));

        jComboBox3.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(5, 20, 42));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 200, 35));

        cityField.setBackground(new java.awt.Color(255, 255, 255));
        cityField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cityField.setForeground(new java.awt.Color(5, 20, 42));
        cityField.setMaximumRowCount(10);
        cityField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select City/Municipality" }));
        cityField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(cityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 200, 35));

        barangayField.setBackground(new java.awt.Color(255, 255, 255));
        barangayField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        barangayField.setForeground(new java.awt.Color(5, 20, 42));
        barangayField.setMaximumRowCount(10);
        barangayField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Barangay" }));
        barangayField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(barangayField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 35));

        postalCodeField.setBackground(new java.awt.Color(255, 255, 255));
        postalCodeField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        postalCodeField.setForeground(new java.awt.Color(5, 20, 42));
        postalCodeField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0)));
        postalCodeField.setPreferredSize(new java.awt.Dimension(75, 30));
        getContentPane().add(postalCodeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 200, 35));

        confirmPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        confirmPasswordField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        confirmPasswordField.setForeground(new java.awt.Color(5, 20, 42));
        confirmPasswordField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0)));
        getContentPane().add(confirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 200, 35));

        passwordField.setBackground(new java.awt.Color(255, 255, 255));
        passwordField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        passwordField.setForeground(new java.awt.Color(5, 20, 42));
        passwordField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0)));
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 200, 35));

        registerButton.setBackground(new java.awt.Color(1, 31, 82));
        registerButton.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(63, 164, 251), 2, true));
        registerButton.setPreferredSize(new java.awt.Dimension(105, 40));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, 150, -1));

        backButton.setBackground(new java.awt.Color(5, 20, 42));
        backButton.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<");
        backButton.setBorder(null);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        passengerRegistrationFrame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passengerRegistrationFrame.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\UPAir\\src\\main\\java\\assets\\Passenger Registration Page.png")); // NOI18N
        getContentPane().add(passengerRegistrationFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LogIn().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    //--------------------------------------------------------------------------------------------------------------------------------------------
    // GUI Methods
    
    private void loadCities(String province) {
        switch (province) {
            case "Albay" -> addCities(new String[]{
                "Legazpi City", "Tabaco City", "Ligao City", "Bacacay", "Camalig", "Daraga",
                "Guinobatan", "Jovellar", "Libon", "Malilipot", "Malinao", "Manito", "Oas",
                "Pio Duran", "Polangui", "Rapu-Rapu", "Santo Domingo", "Tiwi"
            });
            case "Camarines Norte" -> addCities(new String[]{
                "Daet", "Basud", "Capalonga", "Jose Panganiban", "Labo", "Mercedes",
                "Paracale", "San Lorenzo Ruiz", "San Vicente", "Santa Elena", "Talisay", "Vinzons"
            });
            case "Camarines Sur" -> addCities(new String[]{
                "Naga City", "Iriga City", "Baao", "Balatan", "Bato", "Bula", "Buhi", "Cabusao",
                "Calabanga", "Camaligan", "Canaman", "Caramoan", "Del Gallego", "Gainza",
                "Garchitorena", "Goa", "Lagonoy", "Libmanan", "Lupi", "Magarao", "Milaor",
                "Minalabac", "Nabua", "Ocampo", "Pamplona", "Pasacao", "Pili", "Presentacion",
                "Ragay", "Sagñay", "San Fernando", "San Jose", "Sipocot", "Siruma", "Tigaon", "Tinambac"
            });
            case "Catanduanes" -> addCities(new String[]{
                "Virac", "Bagamanoc", "Baras", "Bato", "Caramoran", "Gigmoto",
                "Pandan", "Panganiban", "San Andres", "San Miguel", "Viga"
            });
            case "Masbate" -> addCities(new String[]{
                "Masbate City", "Aroroy", "Baleno", "Balud", "Batuan", "Cataingan",
                "Cawayan", "Claveria", "Dimasalang", "Esperanza", "Mandaon", "Milagros",
                "Mobo", "Monreal", "Palanas", "Pio V. Corpuz", "Placer", "San Fernando",
                "San Jacinto", "San Pascual", "Uson"
            });
            case "Sorsogon" -> addCities(new String[]{
                "Sorsogon City", "Barcelona", "Bulan", "Bulusan", "Casiguran", "Castilla",
                "Donsol", "Gubat", "Irosin", "Juban", "Magallanes", "Matnog",
                "Pilar", "Prieto Diaz", "Santa Magdalena"
            });
        }
    }
    
    private void addCities(String[] cities) {
        for (String c : cities) cityField.addItem(c);
    }
    
    private void loadBarangays(String city) {
        switch (city) {
            // LEGAZPI CITY – sample
            case "Legazpi City" -> addBarangays(new String[]{
                "Bagumbayan", "Banadero", "Bigaa", "Bañadero", "Bogtong", "Bonot",
                "Cabangan", "Capantawan", "Cruzada", "Dap-Dap", "Gogon", "Homapon",
                "Imalnod", "Kawit-East", "Kawit-West", "Lamba", "Mariawa", "Pawa",
                "Puro", "Sabang", "San Francisco", "Taysan", "Victory Village"
            });

            // NAGA CITY – sample
            case "Naga City" -> addBarangays(new String[]{
                "Abella", "Bagumbayan Norte", "Bagumbayan Sur", "Balatas", "Calauag",
                "Cararayan", "Carolina", "Concepcion Pequeña", "Concepcion Grande",
                "Dayangdang", "Del Rosario", "Lerma", "Mabolo", "Peñafrancia", "San Felipe",
                "Tabuco", "Triangulo"
            });

            // DAET – sample
            case "Daet" -> addBarangays(new String[]{
                "Alawihao", "Awitan", "Bagasbas", "Barangay I", "Barangay II", "Barangay III",
                "Barangay IV", "Barangay V", "Barangay VI", "Barangay VII", "Barangay VIII",
                "Bibinotan", "Borabod", "Camambugan", "Cobangcobang", "Dogongan"
            });

            default -> addBarangays(new String[]{"Barangay data not yet added"});
        }
    }

    private void addBarangays(String[] brgys) {
        for (String b : brgys) barangayField.addItem(b);
    }
    
    //--------------------------------------------------------------------------------------------------------------------------------------------
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> barangayField;
    private javax.swing.JLabel barangayLabel;
    private javax.swing.JComboBox<String> cityField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JTextField contactNumberField;
    private javax.swing.JLabel contactNumberLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField idNumberField;
    private javax.swing.JLabel idNumberLabel;
    private javax.swing.JComboBox<String> idTypeField;
    private javax.swing.JLabel idTypeLabel;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel passengerRegistrationFrame;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField postalCodeField;
    private javax.swing.JLabel postalCodeLabel;
    private javax.swing.JComboBox<String> provinceField;
    private javax.swing.JLabel provinceLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
