package kingsman.upair;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;
        
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author admin
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
        setLocationRelativeTo(null);
        startDateTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        dashboardButton = new javax.swing.JButton();
        manageFlightsButton = new javax.swing.JButton();
        manageSchedulesButton = new javax.swing.JButton();
        manageBookingsButton = new javax.swing.JButton();
        manageSeatsButton = new javax.swing.JButton();
        tabPanel = new javax.swing.JTabbedPane();
        dashboardPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        datetimePanel = new javax.swing.JPanel();
        datetimeLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        activeFlightsPanel = new javax.swing.JPanel();
        activeFlightsLabel = new javax.swing.JLabel();
        activeFlights = new javax.swing.JLabel();
        passengersTodayPanel = new javax.swing.JPanel();
        passengersTodayLabel = new javax.swing.JLabel();
        passengersToday = new javax.swing.JLabel();
        totalRevenuePanel = new javax.swing.JPanel();
        totalRevenueLabel = new javax.swing.JLabel();
        totalRevenue = new javax.swing.JLabel();
        recentFlightsPanel = new javax.swing.JPanel();
        recentFlightsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        manageFlightsPanel = new javax.swing.JPanel();
        airlineSelectorPanel = new javax.swing.JPanel();
        airlineSelectorLabel = new javax.swing.JLabel();
        airAsiaButton = new javax.swing.JButton();
        cebGoButton = new javax.swing.JButton();
        palButton = new javax.swing.JButton();
        flightMaker = new javax.swing.JPanel();
        manageFlightsHeaderPanel = new javax.swing.JPanel();
        manageFlightsHeaderLabel = new javax.swing.JLabel();
        selectedAirlinePanel = new javax.swing.JPanel();
        selectedAirline = new javax.swing.JLabel();
        selectedAirlineLabel = new javax.swing.JLabel();
        addFlightDetailsPanel = new javax.swing.JPanel();
        originLabel = new javax.swing.JLabel();
        destinationLabel = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();
        aircraftModelLabel = new javax.swing.JLabel();
        flightCodeLabel = new javax.swing.JLabel();
        seatCapacityLabel = new javax.swing.JLabel();
        baseFareLabel = new javax.swing.JLabel();
        origin = new javax.swing.JComboBox<>();
        destination = new javax.swing.JComboBox<>();
        duration = new javax.swing.JTextField();
        aircraftModel = new javax.swing.JComboBox<>();
        flightCode = new javax.swing.JTextField();
        seatCapacity = new javax.swing.JTextField();
        baseFare = new javax.swing.JTextField();
        tableScrollPane = new javax.swing.JScrollPane();
        flightTable = new javax.swing.JTable();
        addFlightButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        addFlightOfferPanel = new javax.swing.JPanel();
        cabinClassLabel = new javax.swing.JLabel();
        moreDetailsLabel = new javax.swing.JLabel();
        seatTypeLabel = new javax.swing.JLabel();
        foodAndBeveragesLabel = new javax.swing.JLabel();
        entertainmentLabel = new javax.swing.JLabel();
        amenityLabel = new javax.swing.JLabel();
        cabinClass = new javax.swing.JComboBox<>();
        entertainment = new javax.swing.JComboBox<>();
        seatType = new javax.swing.JComboBox<>();
        amenity = new javax.swing.JComboBox<>();
        foodAndBeverages = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        moreDetails = new javax.swing.JTextArea();
        addOfferButton = new javax.swing.JButton();
        manageSchedulePanel = new javax.swing.JPanel();
        manageFlightsHeaderPanel1 = new javax.swing.JPanel();
        manageFlightsHeaderLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        addOfferButton3 = new javax.swing.JButton();
        addOfferButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        seatTypeLabel1 = new javax.swing.JLabel();
        seatTypeLabel2 = new javax.swing.JLabel();
        seatTypeLabel3 = new javax.swing.JLabel();
        seatTypeLabel4 = new javax.swing.JLabel();
        seatTypeLabel5 = new javax.swing.JLabel();
        foodAndBeverages2 = new javax.swing.JComboBox<>();
        foodAndBeverages3 = new javax.swing.JComboBox<>();
        foodAndBeverages4 = new javax.swing.JComboBox<>();
        seatTypeLabel6 = new javax.swing.JLabel();
        seatTypeLabel7 = new javax.swing.JLabel();
        seatTypeLabel8 = new javax.swing.JLabel();
        foodAndBeverages5 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        addOfferButton2 = new javax.swing.JButton();
        manageBookingsPanel = new javax.swing.JPanel();
        bookingsMainPanel = new javax.swing.JPanel();
        manageBookingsHeaderPanel = new javax.swing.JPanel();
        manageBookingsHeaderLabel = new javax.swing.JLabel();
        bookingsPanel = new javax.swing.JPanel();
        addOfferButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        addOfferButton5 = new javax.swing.JButton();
        addOfferButton6 = new javax.swing.JButton();
        addOfferButton7 = new javax.swing.JButton();
        approvedBookingsHistory = new javax.swing.JPanel();
        recentFlightsLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        addOfferButton8 = new javax.swing.JButton();
        personalBookingDetails = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        seatTypeLabel9 = new javax.swing.JLabel();
        seatTypeLabel10 = new javax.swing.JLabel();
        seatTypeLabel11 = new javax.swing.JLabel();
        seatTypeLabel12 = new javax.swing.JLabel();
        seatTypeLabel13 = new javax.swing.JLabel();
        seatTypeLabel14 = new javax.swing.JLabel();
        seatTypeLabel15 = new javax.swing.JLabel();
        seatTypeLabel16 = new javax.swing.JLabel();
        seatTypeLabel17 = new javax.swing.JLabel();
        seatTypeLabel18 = new javax.swing.JLabel();
        seatTypeLabel19 = new javax.swing.JLabel();
        seatTypeLabel20 = new javax.swing.JLabel();
        seatTypeLabel21 = new javax.swing.JLabel();
        seatTypeLabel22 = new javax.swing.JLabel();
        seatTypeLabel23 = new javax.swing.JLabel();
        seatTypeLabel24 = new javax.swing.JLabel();
        seatTypeLabel25 = new javax.swing.JLabel();
        seatTypeLabel26 = new javax.swing.JLabel();
        selectedAirlineLabel1 = new javax.swing.JLabel();
        selectedAirlineLabel2 = new javax.swing.JLabel();
        addOfferButton9 = new javax.swing.JButton();
        manageSeatsPanel = new javax.swing.JPanel();
        manageSeatsHeaderPanel = new javax.swing.JPanel();
        manageSeatsHeaderLabel = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        addOfferButton10 = new javax.swing.JButton();
        destinationLabel1 = new javax.swing.JLabel();
        flightCode1 = new javax.swing.JTextField();
        destinationLabel2 = new javax.swing.JLabel();
        destinationLabel3 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        destinationLabel4 = new javax.swing.JLabel();
        foodAndBeverages6 = new javax.swing.JComboBox<>();
        foodAndBeverages7 = new javax.swing.JComboBox<>();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPanel.setBackground(new java.awt.Color(5, 20, 42));
        topPanel.setForeground(new java.awt.Color(255, 255, 255));
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLabel.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\UPAir\\src\\main\\java\\assets\\Title.png")); // NOI18N
        topPanel.add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 60));

        getContentPane().add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 60));

        sidePanel.setBackground(new java.awt.Color(11, 56, 118));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardButton.setBackground(new java.awt.Color(255, 255, 255));
        dashboardButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        dashboardButton.setForeground(new java.awt.Color(255, 255, 255));
        dashboardButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\UPAir\\src\\main\\java\\assets\\Home.png")); // NOI18N
        dashboardButton.setText("DASHBOARD");
        dashboardButton.setBorderPainted(false);
        dashboardButton.setContentAreaFilled(false);
        dashboardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboardButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        dashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButtonActionPerformed(evt);
            }
        });
        sidePanel.add(dashboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 250, 40));

        manageFlightsButton.setBackground(new java.awt.Color(255, 255, 255));
        manageFlightsButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        manageFlightsButton.setForeground(new java.awt.Color(255, 255, 255));
        manageFlightsButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\UPAir\\src\\main\\java\\assets\\Plane.png")); // NOI18N
        manageFlightsButton.setText("MANAGE FLIGHTS");
        manageFlightsButton.setBorderPainted(false);
        manageFlightsButton.setContentAreaFilled(false);
        manageFlightsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageFlightsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageFlightsButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        manageFlightsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFlightsButtonActionPerformed(evt);
            }
        });
        sidePanel.add(manageFlightsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 250, 40));

        manageSchedulesButton.setBackground(new java.awt.Color(255, 255, 255));
        manageSchedulesButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        manageSchedulesButton.setForeground(new java.awt.Color(255, 255, 255));
        manageSchedulesButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\UPAir\\src\\main\\java\\assets\\Calendar.png")); // NOI18N
        manageSchedulesButton.setText("MANAGE SCHEDULES");
        manageSchedulesButton.setBorderPainted(false);
        manageSchedulesButton.setContentAreaFilled(false);
        manageSchedulesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageSchedulesButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageSchedulesButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        manageSchedulesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSchedulesButtonActionPerformed(evt);
            }
        });
        sidePanel.add(manageSchedulesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, 40));

        manageBookingsButton.setBackground(new java.awt.Color(255, 255, 255));
        manageBookingsButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        manageBookingsButton.setForeground(new java.awt.Color(255, 255, 255));
        manageBookingsButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\UPAir\\src\\main\\java\\assets\\Ticket.png")); // NOI18N
        manageBookingsButton.setText("MANAGE BOOKINGS");
        manageBookingsButton.setBorderPainted(false);
        manageBookingsButton.setContentAreaFilled(false);
        manageBookingsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageBookingsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageBookingsButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        manageBookingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBookingsButtonActionPerformed(evt);
            }
        });
        sidePanel.add(manageBookingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 250, 40));

        manageSeatsButton.setBackground(new java.awt.Color(255, 255, 255));
        manageSeatsButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        manageSeatsButton.setForeground(new java.awt.Color(255, 255, 255));
        manageSeatsButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\UPAir\\src\\main\\java\\assets\\Seats.png")); // NOI18N
        manageSeatsButton.setText("MANAGE SEATS");
        manageSeatsButton.setBorderPainted(false);
        manageSeatsButton.setContentAreaFilled(false);
        manageSeatsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageSeatsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageSeatsButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        manageSeatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSeatsButtonActionPerformed(evt);
            }
        });
        sidePanel.add(manageSeatsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 250, 40));

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 740));

        dashboardPanel.setBackground(new java.awt.Color(204, 204, 204));
        dashboardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeLabel.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(60, 63, 65));
        welcomeLabel.setText("Hello Administrator!");
        dashboardPanel.add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 300, 40));

        datetimePanel.setBackground(new java.awt.Color(5, 20, 42));
        datetimePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        datetimePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datetimeLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        datetimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        datetimeLabel.setText("SYSTEM DATE AND TIME");
        datetimePanel.add(datetimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

        timeLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(255, 255, 255));
        timeLabel.setText("--:--:-- --");
        datetimePanel.add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 200, 30));

        dateLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setText("------------");
        datetimePanel.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 30));

        dashboardPanel.add(datetimePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 240, 100));

        activeFlightsPanel.setBackground(new java.awt.Color(11, 56, 118));
        activeFlightsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        activeFlightsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        activeFlightsLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        activeFlightsLabel.setForeground(new java.awt.Color(255, 255, 255));
        activeFlightsLabel.setText("ACTIVE FLIGHTS");
        activeFlightsPanel.add(activeFlightsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

        activeFlights.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        activeFlights.setForeground(new java.awt.Color(255, 255, 255));
        activeFlights.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        activeFlights.setText("0");
        activeFlightsPanel.add(activeFlights, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 40));

        dashboardPanel.add(activeFlightsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 220, 100));

        passengersTodayPanel.setBackground(new java.awt.Color(11, 56, 118));
        passengersTodayPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        passengersTodayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passengersTodayLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        passengersTodayLabel.setForeground(new java.awt.Color(255, 255, 255));
        passengersTodayLabel.setText("PASSENGERS TODAY");
        passengersTodayPanel.add(passengersTodayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

        passengersToday.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        passengersToday.setForeground(new java.awt.Color(255, 255, 255));
        passengersToday.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        passengersToday.setText("0");
        passengersTodayPanel.add(passengersToday, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 40));

        dashboardPanel.add(passengersTodayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 220, 100));

        totalRevenuePanel.setBackground(new java.awt.Color(11, 56, 118));
        totalRevenuePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        totalRevenuePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalRevenueLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        totalRevenueLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalRevenueLabel.setText("TOTAL REVENUE");
        totalRevenuePanel.add(totalRevenueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

        totalRevenue.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        totalRevenue.setForeground(new java.awt.Color(255, 255, 255));
        totalRevenue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        totalRevenue.setText("PHP 0.00");
        totalRevenuePanel.add(totalRevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 40));

        dashboardPanel.add(totalRevenuePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 220, 100));

        recentFlightsPanel.setBackground(new java.awt.Color(255, 255, 255));
        recentFlightsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 57, 118), 2));
        recentFlightsPanel.setForeground(new java.awt.Color(255, 255, 255));
        recentFlightsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recentFlightsLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        recentFlightsLabel.setForeground(new java.awt.Color(60, 63, 65));
        recentFlightsLabel.setText("RECENT FLIGHTS");
        recentFlightsPanel.add(recentFlightsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 2, -1, 50));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Flight Number", "Aircraft Model", "Departure  Time", "Destination", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        recentFlightsPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 910, 510));

        dashboardPanel.add(recentFlightsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 930, 570));

        tabPanel.addTab("tab1", dashboardPanel);

        manageFlightsPanel.setBackground(new java.awt.Color(204, 204, 204));
        manageFlightsPanel.setLayout(new java.awt.CardLayout());

        airlineSelectorPanel.setBackground(new java.awt.Color(204, 204, 204));
        airlineSelectorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        airlineSelectorLabel.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        airlineSelectorLabel.setForeground(new java.awt.Color(60, 63, 65));
        airlineSelectorLabel.setText("Select Airline");
        airlineSelectorPanel.add(airlineSelectorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 200, 40));

        airAsiaButton.setBackground(new java.awt.Color(255, 255, 255));
        airAsiaButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        airAsiaButton.setForeground(new java.awt.Color(5, 20, 42));
        airAsiaButton.setText("AIR ASIA");
        airAsiaButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 20, 42), 2, true));
        airAsiaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        airAsiaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        airAsiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airAsiaButtonActionPerformed(evt);
            }
        });
        airlineSelectorPanel.add(airAsiaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 270, 160));

        cebGoButton.setBackground(new java.awt.Color(255, 255, 255));
        cebGoButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        cebGoButton.setForeground(new java.awt.Color(5, 20, 42));
        cebGoButton.setText("CEBU PACIFIC GO");
        cebGoButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 20, 42), 2, true));
        cebGoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cebGoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cebGoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cebGoButtonActionPerformed(evt);
            }
        });
        airlineSelectorPanel.add(cebGoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 270, 160));

        palButton.setBackground(new java.awt.Color(255, 255, 255));
        palButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        palButton.setForeground(new java.awt.Color(5, 20, 42));
        palButton.setText("PHILIPPINE AIRLINES");
        palButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 20, 42), 2, true));
        palButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        palButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        palButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palButtonActionPerformed(evt);
            }
        });
        airlineSelectorPanel.add(palButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 270, 160));

        manageFlightsPanel.add(airlineSelectorPanel, "card3");

        flightMaker.setBackground(new java.awt.Color(255, 255, 255));
        flightMaker.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageFlightsHeaderPanel.setBackground(new java.awt.Color(204, 204, 204));
        manageFlightsHeaderPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        manageFlightsHeaderPanel.setForeground(new java.awt.Color(255, 255, 255));
        manageFlightsHeaderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageFlightsHeaderLabel.setFont(new java.awt.Font("Bahnschrift", 1, 55)); // NOI18N
        manageFlightsHeaderLabel.setForeground(new java.awt.Color(60, 63, 65));
        manageFlightsHeaderLabel.setText("MANAGE FLIGHTS");
        manageFlightsHeaderPanel.add(manageFlightsHeaderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 60));

        flightMaker.add(manageFlightsHeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 910, 70));

        selectedAirlinePanel.setBackground(new java.awt.Color(255, 255, 255));
        selectedAirlinePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        selectedAirlinePanel.setForeground(new java.awt.Color(255, 255, 255));
        selectedAirlinePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectedAirline.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        selectedAirline.setForeground(new java.awt.Color(60, 63, 65));
        selectedAirline.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        selectedAirline.setText("null");
        selectedAirlinePanel.add(selectedAirline, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 240, 30));

        selectedAirlineLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        selectedAirlineLabel.setForeground(new java.awt.Color(60, 63, 65));
        selectedAirlineLabel.setText("Selected Airline:");
        selectedAirlinePanel.add(selectedAirlineLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, 30));

        flightMaker.add(selectedAirlinePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 910, 50));

        addFlightDetailsPanel.setBackground(new java.awt.Color(204, 204, 204));
        addFlightDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Flight Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        addFlightDetailsPanel.setForeground(new java.awt.Color(255, 255, 255));
        addFlightDetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        originLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        originLabel.setForeground(new java.awt.Color(0, 0, 0));
        originLabel.setText("Origin");
        addFlightDetailsPanel.add(originLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        destinationLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        destinationLabel.setForeground(new java.awt.Color(0, 0, 0));
        destinationLabel.setText("Destination");
        addFlightDetailsPanel.add(destinationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        durationLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        durationLabel.setForeground(new java.awt.Color(0, 0, 0));
        durationLabel.setText("Duration");
        addFlightDetailsPanel.add(durationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        aircraftModelLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aircraftModelLabel.setForeground(new java.awt.Color(0, 0, 0));
        aircraftModelLabel.setText("Aircraft Model");
        addFlightDetailsPanel.add(aircraftModelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        flightCodeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        flightCodeLabel.setForeground(new java.awt.Color(0, 0, 0));
        flightCodeLabel.setText("Flight Code");
        addFlightDetailsPanel.add(flightCodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        seatCapacityLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        seatCapacityLabel.setForeground(new java.awt.Color(0, 0, 0));
        seatCapacityLabel.setText("Seat Capacity");
        addFlightDetailsPanel.add(seatCapacityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        baseFareLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        baseFareLabel.setForeground(new java.awt.Color(0, 0, 0));
        baseFareLabel.setText("Base Fare");
        addFlightDetailsPanel.add(baseFareLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        origin.setBackground(new java.awt.Color(255, 255, 255));
        origin.setForeground(new java.awt.Color(0, 0, 0));
        origin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addFlightDetailsPanel.add(origin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 190, 40));

        destination.setBackground(new java.awt.Color(255, 255, 255));
        destination.setForeground(new java.awt.Color(0, 0, 0));
        destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addFlightDetailsPanel.add(destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 190, 40));

        duration.setBackground(new java.awt.Color(255, 255, 255));
        duration.setForeground(new java.awt.Color(0, 0, 0));
        addFlightDetailsPanel.add(duration, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 150, 40));

        aircraftModel.setBackground(new java.awt.Color(255, 255, 255));
        aircraftModel.setForeground(new java.awt.Color(0, 0, 0));
        aircraftModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addFlightDetailsPanel.add(aircraftModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, 40));

        flightCode.setBackground(new java.awt.Color(255, 255, 255));
        flightCode.setForeground(new java.awt.Color(0, 0, 0));
        addFlightDetailsPanel.add(flightCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 150, 40));

        seatCapacity.setBackground(new java.awt.Color(255, 255, 255));
        seatCapacity.setForeground(new java.awt.Color(0, 0, 0));
        addFlightDetailsPanel.add(seatCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 110, 40));

        baseFare.setBackground(new java.awt.Color(255, 255, 255));
        baseFare.setForeground(new java.awt.Color(0, 0, 0));
        addFlightDetailsPanel.add(baseFare, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 110, 40));

        flightTable.setBackground(new java.awt.Color(255, 255, 255));
        flightTable.setForeground(new java.awt.Color(0, 0, 0));
        flightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Aircraft Model", "Flight Code", "Seat Capacity", "Base Fare (in PHP)"
            }
        ));
        tableScrollPane.setViewportView(flightTable);

        addFlightDetailsPanel.add(tableScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 550, 350));

        addFlightButton.setBackground(new java.awt.Color(255, 255, 255));
        addFlightButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addFlightButton.setForeground(new java.awt.Color(5, 20, 42));
        addFlightButton.setText("Add Flight");
        addFlightButton.setBorder(null);
        addFlightButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addFlightButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightButtonActionPerformed(evt);
            }
        });
        addFlightDetailsPanel.add(addFlightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 110, 30));

        deleteButton.setBackground(new java.awt.Color(255, 255, 255));
        deleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(5, 20, 42));
        deleteButton.setText("Delete Selected");
        deleteButton.setBorder(null);
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        addFlightDetailsPanel.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 110, 30));

        editButton.setBackground(new java.awt.Color(255, 255, 255));
        editButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editButton.setForeground(new java.awt.Color(5, 20, 42));
        editButton.setText("Edit Selected");
        editButton.setBorder(null);
        editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        addFlightDetailsPanel.add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 110, 30));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(5, 20, 42));
        backButton.setText("Back");
        backButton.setBorder(null);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        addFlightDetailsPanel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 90, 30));

        flightMaker.add(addFlightDetailsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 580, 580));

        addFlightOfferPanel.setBackground(new java.awt.Color(204, 204, 204));
        addFlightOfferPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Flight Offer Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        addFlightOfferPanel.setForeground(new java.awt.Color(255, 255, 255));
        addFlightOfferPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cabinClassLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cabinClassLabel.setForeground(new java.awt.Color(0, 0, 0));
        cabinClassLabel.setText("Cabin Class");
        addFlightOfferPanel.add(cabinClassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        moreDetailsLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        moreDetailsLabel.setForeground(new java.awt.Color(0, 0, 0));
        moreDetailsLabel.setText("Add More Details");
        addFlightOfferPanel.add(moreDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        seatTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        seatTypeLabel.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel.setText("Seat Type");
        addFlightOfferPanel.add(seatTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        foodAndBeveragesLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        foodAndBeveragesLabel.setForeground(new java.awt.Color(0, 0, 0));
        foodAndBeveragesLabel.setText("Food and Beverages");
        addFlightOfferPanel.add(foodAndBeveragesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        entertainmentLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        entertainmentLabel.setForeground(new java.awt.Color(0, 0, 0));
        entertainmentLabel.setText("Entertainment");
        addFlightOfferPanel.add(entertainmentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        amenityLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        amenityLabel.setForeground(new java.awt.Color(0, 0, 0));
        amenityLabel.setText("Amenity");
        addFlightOfferPanel.add(amenityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        cabinClass.setBackground(new java.awt.Color(255, 255, 255));
        cabinClass.setForeground(new java.awt.Color(0, 0, 0));
        cabinClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addFlightOfferPanel.add(cabinClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 140, 40));

        entertainment.setBackground(new java.awt.Color(255, 255, 255));
        entertainment.setForeground(new java.awt.Color(0, 0, 0));
        entertainment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addFlightOfferPanel.add(entertainment, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 140, 40));

        seatType.setBackground(new java.awt.Color(255, 255, 255));
        seatType.setForeground(new java.awt.Color(0, 0, 0));
        seatType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addFlightOfferPanel.add(seatType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, 40));

        amenity.setBackground(new java.awt.Color(255, 255, 255));
        amenity.setForeground(new java.awt.Color(0, 0, 0));
        amenity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addFlightOfferPanel.add(amenity, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 140, 40));

        foodAndBeverages.setBackground(new java.awt.Color(255, 255, 255));
        foodAndBeverages.setForeground(new java.awt.Color(0, 0, 0));
        foodAndBeverages.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addFlightOfferPanel.add(foodAndBeverages, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 140, 40));

        moreDetails.setBackground(new java.awt.Color(255, 255, 255));
        moreDetails.setColumns(20);
        moreDetails.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        moreDetails.setForeground(new java.awt.Color(0, 0, 0));
        moreDetails.setRows(5);
        moreDetails.setText("Enter text");
        jScrollPane3.setViewportView(moreDetails);

        addFlightOfferPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 300, 210));

        addOfferButton.setBackground(new java.awt.Color(255, 255, 255));
        addOfferButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addOfferButton.setForeground(new java.awt.Color(5, 20, 42));
        addOfferButton.setText("Add Offer");
        addOfferButton.setBorder(null);
        addOfferButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addOfferButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addOfferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOfferButtonActionPerformed(evt);
            }
        });
        addFlightOfferPanel.add(addOfferButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 110, 30));

        flightMaker.add(addFlightOfferPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 320, 580));

        manageFlightsPanel.add(flightMaker, "card2");

        tabPanel.addTab("tab2", manageFlightsPanel);

        manageSchedulePanel.setBackground(new java.awt.Color(255, 255, 255));
        manageSchedulePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageFlightsHeaderPanel1.setBackground(new java.awt.Color(204, 204, 204));
        manageFlightsHeaderPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        manageFlightsHeaderPanel1.setForeground(new java.awt.Color(255, 255, 255));
        manageFlightsHeaderPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageFlightsHeaderLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 55)); // NOI18N
        manageFlightsHeaderLabel1.setForeground(new java.awt.Color(60, 63, 65));
        manageFlightsHeaderLabel1.setText("MANAGE SCHEDULES");
        manageFlightsHeaderPanel1.add(manageFlightsHeaderLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 60));

        manageSchedulePanel.add(manageFlightsHeaderPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 910, 70));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Scheduled Flights", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setBackground(new java.awt.Color(255, 255, 255));
        jTable2.setForeground(new java.awt.Color(0, 0, 0));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Airline", "Flight Code", "Origin", "Destination", "Date", "Departure Time"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 580, 510));

        addOfferButton3.setBackground(new java.awt.Color(255, 255, 255));
        addOfferButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addOfferButton3.setForeground(new java.awt.Color(5, 20, 42));
        addOfferButton3.setText("Delete Selected");
        addOfferButton3.setBorder(null);
        addOfferButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addOfferButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addOfferButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOfferButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(addOfferButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 130, 30));

        addOfferButton1.setBackground(new java.awt.Color(255, 255, 255));
        addOfferButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addOfferButton1.setForeground(new java.awt.Color(5, 20, 42));
        addOfferButton1.setText("Edit Selected");
        addOfferButton1.setBorder(null);
        addOfferButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addOfferButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addOfferButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOfferButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(addOfferButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, 130, 30));

        manageSchedulePanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 600, 590));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Flight Schedule", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seatTypeLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        seatTypeLabel1.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel1.setText("Time");
        jPanel2.add(seatTypeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        seatTypeLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        seatTypeLabel2.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel2.setText("Airline:");
        jPanel2.add(seatTypeLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        seatTypeLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        seatTypeLabel3.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel3.setText("Flight Code:");
        jPanel2.add(seatTypeLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        seatTypeLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        seatTypeLabel4.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel4.setText("Origin:");
        jPanel2.add(seatTypeLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        seatTypeLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        seatTypeLabel5.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel5.setText("Destination:");
        jPanel2.add(seatTypeLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        foodAndBeverages2.setBackground(new java.awt.Color(255, 255, 255));
        foodAndBeverages2.setForeground(new java.awt.Color(0, 0, 0));
        foodAndBeverages2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(foodAndBeverages2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 160, 30));

        foodAndBeverages3.setBackground(new java.awt.Color(255, 255, 255));
        foodAndBeverages3.setForeground(new java.awt.Color(0, 0, 0));
        foodAndBeverages3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(foodAndBeverages3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 160, 30));

        foodAndBeverages4.setBackground(new java.awt.Color(255, 255, 255));
        foodAndBeverages4.setForeground(new java.awt.Color(0, 0, 0));
        foodAndBeverages4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(foodAndBeverages4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 160, 30));

        seatTypeLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        seatTypeLabel6.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel6.setText("Details");
        jPanel2.add(seatTypeLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        seatTypeLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        seatTypeLabel7.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel7.setText("Departure");
        jPanel2.add(seatTypeLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        seatTypeLabel8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        seatTypeLabel8.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel8.setText("Date ");
        jPanel2.add(seatTypeLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        foodAndBeverages5.setBackground(new java.awt.Color(255, 255, 255));
        foodAndBeverages5.setForeground(new java.awt.Color(0, 0, 0));
        foodAndBeverages5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(foodAndBeverages5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 160, 30));

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 160, 30));

        jSpinner1.setToolTipText("");
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 70, -1));
        jPanel2.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 70, -1));

        addOfferButton2.setBackground(new java.awt.Color(255, 255, 255));
        addOfferButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addOfferButton2.setForeground(new java.awt.Color(5, 20, 42));
        addOfferButton2.setText("Add Schedule");
        addOfferButton2.setBorder(null);
        addOfferButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addOfferButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addOfferButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOfferButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(addOfferButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 140, 30));

        manageSchedulePanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 300, 450));

        tabPanel.addTab("tab3", manageSchedulePanel);

        manageBookingsPanel.setBackground(new java.awt.Color(255, 255, 255));
        manageBookingsPanel.setLayout(new java.awt.CardLayout());

        bookingsMainPanel.setBackground(new java.awt.Color(153, 153, 153));
        bookingsMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageBookingsHeaderPanel.setBackground(new java.awt.Color(204, 204, 204));
        manageBookingsHeaderPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        manageBookingsHeaderPanel.setForeground(new java.awt.Color(255, 255, 255));
        manageBookingsHeaderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageBookingsHeaderLabel.setFont(new java.awt.Font("Bahnschrift", 1, 55)); // NOI18N
        manageBookingsHeaderLabel.setForeground(new java.awt.Color(60, 63, 65));
        manageBookingsHeaderLabel.setText("MANAGE BOOKINGS");
        manageBookingsHeaderPanel.add(manageBookingsHeaderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 60));

        bookingsMainPanel.add(manageBookingsHeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 910, 70));

        bookingsPanel.setBackground(new java.awt.Color(204, 204, 204));
        bookingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bookings", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        bookingsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addOfferButton4.setBackground(new java.awt.Color(255, 255, 255));
        addOfferButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addOfferButton4.setForeground(new java.awt.Color(5, 20, 42));
        addOfferButton4.setText("View Selected");
        addOfferButton4.setBorder(null);
        addOfferButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addOfferButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addOfferButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOfferButton4ActionPerformed(evt);
            }
        });
        bookingsPanel.add(addOfferButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 610, 140, 30));

        jTable3.setBackground(new java.awt.Color(255, 255, 255));
        jTable3.setForeground(new java.awt.Color(0, 0, 0));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Booking ID", "Name", "Route", "Category", "Flight Date", "Payment", "No. of Passenger"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        bookingsPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 890, 570));

        addOfferButton5.setBackground(new java.awt.Color(255, 255, 255));
        addOfferButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addOfferButton5.setForeground(new java.awt.Color(5, 20, 42));
        addOfferButton5.setText("Approved History");
        addOfferButton5.setBorder(null);
        addOfferButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addOfferButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addOfferButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOfferButton5ActionPerformed(evt);
            }
        });
        bookingsPanel.add(addOfferButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 610, 140, 30));

        addOfferButton6.setBackground(new java.awt.Color(255, 255, 255));
        addOfferButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addOfferButton6.setForeground(new java.awt.Color(5, 20, 42));
        addOfferButton6.setText("Cancel Selected");
        addOfferButton6.setBorder(null);
        addOfferButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addOfferButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addOfferButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOfferButton6ActionPerformed(evt);
            }
        });
        bookingsPanel.add(addOfferButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 610, 140, 30));

        addOfferButton7.setBackground(new java.awt.Color(255, 255, 255));
        addOfferButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addOfferButton7.setForeground(new java.awt.Color(5, 20, 42));
        addOfferButton7.setText("Approve Selected");
        addOfferButton7.setBorder(null);
        addOfferButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addOfferButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addOfferButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOfferButton7ActionPerformed(evt);
            }
        });
        bookingsPanel.add(addOfferButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, 140, 30));

        bookingsMainPanel.add(bookingsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 910, 650));

        manageBookingsPanel.add(bookingsMainPanel, "card2");

        approvedBookingsHistory.setBackground(new java.awt.Color(204, 204, 204));
        approvedBookingsHistory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recentFlightsLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        recentFlightsLabel1.setForeground(new java.awt.Color(60, 63, 65));
        recentFlightsLabel1.setText("Approved Bookings History");
        approvedBookingsHistory.add(recentFlightsLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, 40));

        jTable4.setBackground(new java.awt.Color(255, 255, 255));
        jTable4.setForeground(new java.awt.Color(0, 0, 0));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Booking ID", "Name", "Route", "Category", "Flight Date", "Payment", "No. of Passenger"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        approvedBookingsHistory.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 890, 620));

        addOfferButton8.setBackground(new java.awt.Color(255, 255, 255));
        addOfferButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addOfferButton8.setForeground(new java.awt.Color(5, 20, 42));
        addOfferButton8.setText("Back To Bookings");
        addOfferButton8.setBorder(null);
        addOfferButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addOfferButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addOfferButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOfferButton8ActionPerformed(evt);
            }
        });
        approvedBookingsHistory.add(addOfferButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 690, 390, 40));

        manageBookingsPanel.add(approvedBookingsHistory, "card3");

        personalBookingDetails.setBackground(new java.awt.Color(204, 204, 204));
        personalBookingDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\UPAir\\src\\main\\java\\assets\\Profile Icon Big.png")); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 120));

        personalBookingDetails.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 120));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal and Booking Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seatTypeLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        seatTypeLabel9.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        seatTypeLabel9.setText("FLIGHT DATE:");
        jPanel4.add(seatTypeLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        seatTypeLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        seatTypeLabel10.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        seatTypeLabel10.setText("No special requests");
        jPanel4.add(seatTypeLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, -1));

        seatTypeLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        seatTypeLabel11.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        seatTypeLabel11.setText("ROUTE:");
        jPanel4.add(seatTypeLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        seatTypeLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        seatTypeLabel12.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        seatTypeLabel12.setText("CATEGORY:");
        jPanel4.add(seatTypeLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        seatTypeLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        seatTypeLabel13.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        seatTypeLabel13.setText("OTHER INFO:");
        jPanel4.add(seatTypeLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, 20));

        seatTypeLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        seatTypeLabel14.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        seatTypeLabel14.setText("PAYNENT:");
        jPanel4.add(seatTypeLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 90, 20));

        seatTypeLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        seatTypeLabel15.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        seatTypeLabel15.setText("NO. OF PASSENGER:");
        jPanel4.add(seatTypeLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, 20));

        seatTypeLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        seatTypeLabel16.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        seatTypeLabel16.setText("PASSENGERS BOOKED:");
        jPanel4.add(seatTypeLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, 20));

        seatTypeLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        seatTypeLabel17.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        seatTypeLabel17.setText("SEATS:");
        jPanel4.add(seatTypeLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, 20));

        seatTypeLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        seatTypeLabel18.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        seatTypeLabel18.setText("ADDRESS:");
        jPanel4.add(seatTypeLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        seatTypeLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        seatTypeLabel19.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        seatTypeLabel19.setText("Address, City, Country");
        jPanel4.add(seatTypeLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        seatTypeLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        seatTypeLabel20.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        seatTypeLabel20.setText("MNL - CRK");
        jPanel4.add(seatTypeLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        seatTypeLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        seatTypeLabel21.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        seatTypeLabel21.setText("One Way");
        jPanel4.add(seatTypeLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        seatTypeLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        seatTypeLabel22.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        seatTypeLabel22.setText("2025-12-25");
        jPanel4.add(seatTypeLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        seatTypeLabel23.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        seatTypeLabel23.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        seatTypeLabel23.setText("Online");
        jPanel4.add(seatTypeLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        seatTypeLabel24.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        seatTypeLabel24.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        seatTypeLabel24.setText("3");
        jPanel4.add(seatTypeLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        seatTypeLabel25.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        seatTypeLabel25.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        seatTypeLabel25.setText("Passenger1, Passenger2");
        jPanel4.add(seatTypeLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));

        seatTypeLabel26.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        seatTypeLabel26.setForeground(new java.awt.Color(0, 0, 0));
        seatTypeLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        seatTypeLabel26.setText("A1, A2, A3");
        jPanel4.add(seatTypeLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        personalBookingDetails.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 910, 520));

        selectedAirlineLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        selectedAirlineLabel1.setForeground(new java.awt.Color(60, 63, 65));
        selectedAirlineLabel1.setText("Booking ID: BK003");
        personalBookingDetails.add(selectedAirlineLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 240, 30));

        selectedAirlineLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        selectedAirlineLabel2.setForeground(new java.awt.Color(60, 63, 65));
        selectedAirlineLabel2.setText("John Doe");
        personalBookingDetails.add(selectedAirlineLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 240, 30));

        addOfferButton9.setBackground(new java.awt.Color(255, 255, 255));
        addOfferButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addOfferButton9.setForeground(new java.awt.Color(5, 20, 42));
        addOfferButton9.setText("Back To Bookings");
        addOfferButton9.setBorder(null);
        addOfferButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addOfferButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addOfferButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOfferButton9ActionPerformed(evt);
            }
        });
        personalBookingDetails.add(addOfferButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 690, 390, 40));

        manageBookingsPanel.add(personalBookingDetails, "card4");

        tabPanel.addTab("tab4", manageBookingsPanel);

        manageSeatsPanel.setBackground(new java.awt.Color(255, 255, 255));
        manageSeatsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageSeatsHeaderPanel.setBackground(new java.awt.Color(204, 204, 204));
        manageSeatsHeaderPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        manageSeatsHeaderPanel.setForeground(new java.awt.Color(255, 255, 255));
        manageSeatsHeaderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageSeatsHeaderLabel.setFont(new java.awt.Font("Bahnschrift", 1, 55)); // NOI18N
        manageSeatsHeaderLabel.setForeground(new java.awt.Color(60, 63, 65));
        manageSeatsHeaderLabel.setText("MANAGE SEATS");
        manageSeatsHeaderPanel.add(manageSeatsHeaderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 60));

        manageSeatsPanel.add(manageSeatsHeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 910, 70));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new java.awt.GridLayout(25, 2, 1, 0));
        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 660));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 150, 670));

        jScrollPane7.setViewportView(jPanel6);

        manageSeatsPanel.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 340, 620));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manage Seats", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable5.setBackground(new java.awt.Color(255, 255, 255));
        jTable5.setForeground(new java.awt.Color(0, 0, 0));
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Airline", "Flight Code", "Origin", "Destination", "Date", "Departure Time"
            }
        ));
        jScrollPane6.setViewportView(jTable5);

        jPanel5.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 550, 370));

        addOfferButton10.setBackground(new java.awt.Color(255, 255, 255));
        addOfferButton10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addOfferButton10.setForeground(new java.awt.Color(5, 20, 42));
        addOfferButton10.setText("View Selected");
        addOfferButton10.setBorder(null);
        addOfferButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addOfferButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addOfferButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOfferButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(addOfferButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 130, 30));

        destinationLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        destinationLabel1.setForeground(new java.awt.Color(0, 0, 0));
        destinationLabel1.setText("Date");
        jPanel5.add(destinationLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, 20));

        flightCode1.setBackground(new java.awt.Color(255, 255, 255));
        flightCode1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(flightCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 200, 40));

        destinationLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        destinationLabel2.setForeground(new java.awt.Color(0, 0, 0));
        destinationLabel2.setText("Search Schedule ID:");
        jPanel5.add(destinationLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, 40));

        destinationLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        destinationLabel3.setForeground(new java.awt.Color(0, 0, 0));
        destinationLabel3.setText("Origin");
        jPanel5.add(destinationLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));
        jPanel5.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 150, 40));

        destinationLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        destinationLabel4.setForeground(new java.awt.Color(0, 0, 0));
        destinationLabel4.setText("Destination");
        jPanel5.add(destinationLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, 20));

        foodAndBeverages6.setBackground(new java.awt.Color(255, 255, 255));
        foodAndBeverages6.setForeground(new java.awt.Color(0, 0, 0));
        foodAndBeverages6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(foodAndBeverages6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 170, 40));

        foodAndBeverages7.setBackground(new java.awt.Color(255, 255, 255));
        foodAndBeverages7.setForeground(new java.awt.Color(0, 0, 0));
        foodAndBeverages7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(foodAndBeverages7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 170, 40));

        manageSeatsPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 570, 620));

        tabPanel.addTab("tab5", manageSeatsPanel);

        getContentPane().add(tabPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 21, 950, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
        tabPanel.setSelectedIndex(0);
    }//GEN-LAST:event_dashboardButtonActionPerformed

    private void manageFlightsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFlightsButtonActionPerformed
        tabPanel.setSelectedIndex(1);
    }//GEN-LAST:event_manageFlightsButtonActionPerformed

    private void manageSchedulesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSchedulesButtonActionPerformed
        tabPanel.setSelectedIndex(2);
    }//GEN-LAST:event_manageSchedulesButtonActionPerformed

    private void manageSeatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSeatsButtonActionPerformed
        tabPanel.setSelectedIndex(4);
    }//GEN-LAST:event_manageSeatsButtonActionPerformed

    private void manageBookingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBookingsButtonActionPerformed
        tabPanel.setSelectedIndex(3);
    }//GEN-LAST:event_manageBookingsButtonActionPerformed

    private void airAsiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airAsiaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airAsiaButtonActionPerformed

    private void cebGoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cebGoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cebGoButtonActionPerformed

    private void palButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_palButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void addFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFlightButtonActionPerformed

    private void addOfferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOfferButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addOfferButtonActionPerformed

    private void addOfferButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOfferButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addOfferButton1ActionPerformed

    private void addOfferButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOfferButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addOfferButton2ActionPerformed

    private void addOfferButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOfferButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addOfferButton3ActionPerformed

    private void addOfferButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOfferButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addOfferButton4ActionPerformed

    private void addOfferButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOfferButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addOfferButton5ActionPerformed

    private void addOfferButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOfferButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addOfferButton6ActionPerformed

    private void addOfferButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOfferButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addOfferButton7ActionPerformed

    private void addOfferButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOfferButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addOfferButton8ActionPerformed

    private void addOfferButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOfferButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addOfferButton9ActionPerformed

    private void addOfferButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOfferButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addOfferButton10ActionPerformed
    
    
    private void startDateTime() {

        DateTimeFormatter timeFormat =
                DateTimeFormatter.ofPattern("hh:mm:ss a");

        DateTimeFormatter dateFormat =
                DateTimeFormatter.ofPattern("MMMM dd yyyy");

        Timer timer = new Timer(1000, e -> {
            LocalDateTime now = LocalDateTime.now();

            timeLabel.setText(now.format(timeFormat));
            dateLabel.setText(now.format(dateFormat).toUpperCase());
        });

        timer.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activeFlights;
    private javax.swing.JLabel activeFlightsLabel;
    private javax.swing.JPanel activeFlightsPanel;
    private javax.swing.JButton addFlightButton;
    private javax.swing.JPanel addFlightDetailsPanel;
    private javax.swing.JPanel addFlightOfferPanel;
    private javax.swing.JButton addOfferButton;
    private javax.swing.JButton addOfferButton1;
    private javax.swing.JButton addOfferButton10;
    private javax.swing.JButton addOfferButton2;
    private javax.swing.JButton addOfferButton3;
    private javax.swing.JButton addOfferButton4;
    private javax.swing.JButton addOfferButton5;
    private javax.swing.JButton addOfferButton6;
    private javax.swing.JButton addOfferButton7;
    private javax.swing.JButton addOfferButton8;
    private javax.swing.JButton addOfferButton9;
    private javax.swing.JButton airAsiaButton;
    private javax.swing.JComboBox<String> aircraftModel;
    private javax.swing.JLabel aircraftModelLabel;
    private javax.swing.JLabel airlineSelectorLabel;
    private javax.swing.JPanel airlineSelectorPanel;
    private javax.swing.JComboBox<String> amenity;
    private javax.swing.JLabel amenityLabel;
    private javax.swing.JPanel approvedBookingsHistory;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField baseFare;
    private javax.swing.JLabel baseFareLabel;
    private javax.swing.JPanel bookingsMainPanel;
    private javax.swing.JPanel bookingsPanel;
    private javax.swing.JComboBox<String> cabinClass;
    private javax.swing.JLabel cabinClassLabel;
    private javax.swing.JButton cebGoButton;
    private javax.swing.JButton dashboardButton;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel datetimeLabel;
    private javax.swing.JPanel datetimePanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox<String> destination;
    private javax.swing.JLabel destinationLabel;
    private javax.swing.JLabel destinationLabel1;
    private javax.swing.JLabel destinationLabel2;
    private javax.swing.JLabel destinationLabel3;
    private javax.swing.JLabel destinationLabel4;
    private javax.swing.JTextField duration;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JButton editButton;
    private javax.swing.JComboBox<String> entertainment;
    private javax.swing.JLabel entertainmentLabel;
    private javax.swing.JTextField flightCode;
    private javax.swing.JTextField flightCode1;
    private javax.swing.JLabel flightCodeLabel;
    private javax.swing.JPanel flightMaker;
    private javax.swing.JTable flightTable;
    private javax.swing.JComboBox<String> foodAndBeverages;
    private javax.swing.JComboBox<String> foodAndBeverages2;
    private javax.swing.JComboBox<String> foodAndBeverages3;
    private javax.swing.JComboBox<String> foodAndBeverages4;
    private javax.swing.JComboBox<String> foodAndBeverages5;
    private javax.swing.JComboBox<String> foodAndBeverages6;
    private javax.swing.JComboBox<String> foodAndBeverages7;
    private javax.swing.JLabel foodAndBeveragesLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JButton manageBookingsButton;
    private javax.swing.JLabel manageBookingsHeaderLabel;
    private javax.swing.JPanel manageBookingsHeaderPanel;
    private javax.swing.JPanel manageBookingsPanel;
    private javax.swing.JButton manageFlightsButton;
    private javax.swing.JLabel manageFlightsHeaderLabel;
    private javax.swing.JLabel manageFlightsHeaderLabel1;
    private javax.swing.JPanel manageFlightsHeaderPanel;
    private javax.swing.JPanel manageFlightsHeaderPanel1;
    private javax.swing.JPanel manageFlightsPanel;
    private javax.swing.JPanel manageSchedulePanel;
    private javax.swing.JButton manageSchedulesButton;
    private javax.swing.JButton manageSeatsButton;
    private javax.swing.JLabel manageSeatsHeaderLabel;
    private javax.swing.JPanel manageSeatsHeaderPanel;
    private javax.swing.JPanel manageSeatsPanel;
    private javax.swing.JTextArea moreDetails;
    private javax.swing.JLabel moreDetailsLabel;
    private javax.swing.JComboBox<String> origin;
    private javax.swing.JLabel originLabel;
    private javax.swing.JButton palButton;
    private javax.swing.JLabel passengersToday;
    private javax.swing.JLabel passengersTodayLabel;
    private javax.swing.JPanel passengersTodayPanel;
    private javax.swing.JPanel personalBookingDetails;
    private javax.swing.JLabel recentFlightsLabel;
    private javax.swing.JLabel recentFlightsLabel1;
    private javax.swing.JPanel recentFlightsPanel;
    private javax.swing.JTextField seatCapacity;
    private javax.swing.JLabel seatCapacityLabel;
    private javax.swing.JComboBox<String> seatType;
    private javax.swing.JLabel seatTypeLabel;
    private javax.swing.JLabel seatTypeLabel1;
    private javax.swing.JLabel seatTypeLabel10;
    private javax.swing.JLabel seatTypeLabel11;
    private javax.swing.JLabel seatTypeLabel12;
    private javax.swing.JLabel seatTypeLabel13;
    private javax.swing.JLabel seatTypeLabel14;
    private javax.swing.JLabel seatTypeLabel15;
    private javax.swing.JLabel seatTypeLabel16;
    private javax.swing.JLabel seatTypeLabel17;
    private javax.swing.JLabel seatTypeLabel18;
    private javax.swing.JLabel seatTypeLabel19;
    private javax.swing.JLabel seatTypeLabel2;
    private javax.swing.JLabel seatTypeLabel20;
    private javax.swing.JLabel seatTypeLabel21;
    private javax.swing.JLabel seatTypeLabel22;
    private javax.swing.JLabel seatTypeLabel23;
    private javax.swing.JLabel seatTypeLabel24;
    private javax.swing.JLabel seatTypeLabel25;
    private javax.swing.JLabel seatTypeLabel26;
    private javax.swing.JLabel seatTypeLabel3;
    private javax.swing.JLabel seatTypeLabel4;
    private javax.swing.JLabel seatTypeLabel5;
    private javax.swing.JLabel seatTypeLabel6;
    private javax.swing.JLabel seatTypeLabel7;
    private javax.swing.JLabel seatTypeLabel8;
    private javax.swing.JLabel seatTypeLabel9;
    private javax.swing.JLabel selectedAirline;
    private javax.swing.JLabel selectedAirlineLabel;
    private javax.swing.JLabel selectedAirlineLabel1;
    private javax.swing.JLabel selectedAirlineLabel2;
    private javax.swing.JPanel selectedAirlinePanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel totalRevenue;
    private javax.swing.JLabel totalRevenueLabel;
    private javax.swing.JPanel totalRevenuePanel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
