/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kingsman.upair;

/**
 *
 * @author admin
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form PassengerDashboardFrame
     */
    public AdminDashboard() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    int menuWidth = 0;
    boolean isExpanded = false;
    javax.swing.Timer timer;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sakayLabel = new javax.swing.JLabel();
        toggleLabel = new javax.swing.JLabel();
        searchLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        dividerLabel = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sakayLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\UPAir\\src\\main\\java\\assets\\UPAir Logo.png")); // NOI18N
        getContentPane().add(sakayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        toggleLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\SaKaY\\src\\main\\java\\assets\\ToggleButton.png")); // NOI18N
        toggleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleLabelMouseClicked(evt);
            }
        });
        getContentPane().add(toggleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        searchLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\SaKaY\\src\\main\\java\\assets\\Search  Button.png")); // NOI18N
        searchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchLabelMouseClicked(evt);
            }
        });
        getContentPane().add(searchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, -1, 30));

        welcomeLabel.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        welcomeLabel.setText("Welcome, Juan!");
        getContentPane().add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, -1, -1));

        dividerLabel.setFont(new java.awt.Font("Arial Narrow", 0, 48)); // NOI18N
        dividerLabel.setForeground(new java.awt.Color(63, 164, 251));
        dividerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dividerLabel.setText("|");
        getContentPane().add(dividerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 30, 80));

        sidePanel.setBackground(new java.awt.Color(1, 31, 82));
        sidePanel.setPreferredSize(new java.awt.Dimension(250, 520));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 520));

        topPanel.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\UPAir\\src\\main\\java\\assets\\Top Bar.png")); // NOI18N
        getContentPane().add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 80));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 900, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toggleLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleLabelMouseClicked
        // TODO add your handling code here:
        if (isExpanded) {
            animateMenu(false);
        } else {
            animateMenu(true);
        }
    }//GEN-LAST:event_toggleLabelMouseClicked

    private void searchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchLabelMouseClicked

    private void animateMenu(boolean expand) {
        if (timer != null && timer.isRunning()) {
            return;
        }

        timer = new javax.swing.Timer(0, null);

        timer.addActionListener(e -> {
            if (expand) {
                if (menuWidth < 250) {
                    menuWidth++;
                    sidePanel.setSize(menuWidth, 520);
                } else {
                    isExpanded = true;
                    timer.stop();
                }
            } else {
                if (menuWidth > 0) {
                    menuWidth--;
                    sidePanel.setSize(menuWidth, 520);
                } else {
                    isExpanded = false;
                    timer.stop();
                }
            }
        });

        timer.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dividerLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel sakayLabel;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel toggleLabel;
    private javax.swing.JLabel topPanel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}