/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kingsman.upair;

import javax.swing.JOptionPane;
import kingsman.upair.repository.AdminRepository;
import kingsman.upair.service.PassengerLoginService;

/**
 * Login Frame for both passenger and admin login
 * 
 * @author admin
 */
public class LogInFrame extends javax.swing.JFrame {

    /**
     * Creates new form LogInFrame
     */
    public LogInFrame() {
        initComponents();
        setLocationRelativeTo(null);
        // Initialize admin data files if they don't exist
        AdminRepository.initializeAdminData();
        AdminRepository.initializeAdminPins();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        signInLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        logInButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeLabel.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(11, 56, 118));
        welcomeLabel.setText("Welcome Back!");
        jPanel1.add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 320, -1));

        signInLabel.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        signInLabel.setForeground(new java.awt.Color(102, 102, 102));
        signInLabel.setText("Sign in to your account");
        jPanel1.add(signInLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 210, 50));

        userNameTextField.setBackground(new java.awt.Color(255, 255, 255));
        userNameTextField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        userNameTextField.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(userNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 450, 50));

        passwordField.setBackground(new java.awt.Color(255, 255, 255));
        passwordField.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        passwordField.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 450, 50));

        usernameLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(11, 56, 118));
        usernameLabel.setText("Username");
        jPanel1.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 70, 30));

        passwordLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(11, 56, 118));
        passwordLabel.setText("Password");
        jPanel1.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 70, 30));

        registerButton.setBackground(new java.awt.Color(255, 255, 255));
        registerButton.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        registerButton.setForeground(new java.awt.Color(11, 56, 118));
        registerButton.setText("Don't have an account? Register");
        registerButton.setBorderPainted(false);
        registerButton.setContentAreaFilled(false);
        registerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, 450, 50));

        logInButton.setBackground(new java.awt.Color(11, 56, 118));
        logInButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        logInButton.setForeground(new java.awt.Color(255, 255, 255));
        logInButton.setText("Log In");
        logInButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 450, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // Navigate to registration frame
        this.dispose();
        new RegisterFrame().setVisible(true);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        String username = userNameTextField.getText().trim();
        String password = new String(passwordField.getPassword());
        
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please enter both username and password!", 
                "Login Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Check if admin login
        if (AdminRepository.validateAdmin(username, password)) {
            // Request PIN verification
            String pin = JOptionPane.showInputDialog(this, 
                "Enter administration PIN (6 characters):", 
                "Admin PIN Verification", 
                JOptionPane.QUESTION_MESSAGE);
            
            if (pin == null || pin.trim().isEmpty()) {
                return; // User cancelled
            }
            
            pin = pin.trim();
            if (pin.length() != 6) {
                JOptionPane.showMessageDialog(this, 
                    "PIN must be exactly 6 characters!", 
                    "PIN Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Validate and consume PIN
            if (AdminRepository.validateAndConsumePin(pin)) {
                int remainingPins = AdminRepository.getRemainingPinCount();
                JOptionPane.showMessageDialog(this, 
                    "PIN verified successfully!\nRemaining PINs: " + remainingPins, 
                    "Success", JOptionPane.INFORMATION_MESSAGE);
                
                // Navigate to AdminFrame
                this.dispose();
                new AdminFrame().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Invalid PIN! Please try again.", 
                    "PIN Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Check passenger login
            if (PassengerLoginService.validatePassenger(username, password)) {
                // Navigate to PassengerFrame
                this.dispose();
                new PassengerFrame(username).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Invalid credentials! Please check your username and password.", 
                    "Login Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_logInButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logInButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel signInLabel;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
