/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kingsman.upair;

/**
 *
 * @author admin
 */
public class PassengerDashboard extends javax.swing.JFrame {

    /**
     * Creates new form PassengerDashboardFrame
     */
    public PassengerDashboard() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    int menuWidth = 0;
    boolean isExpanded = false;
    javax.swing.Timer timer;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sakayLabel = new javax.swing.JLabel();
        toggleLabel = new javax.swing.JLabel();
        searchLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        dividerLabel = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        dashboardButton = new javax.swing.JLabel();
        flightsButton = new javax.swing.JLabel();
        myBookingsButton = new javax.swing.JLabel();
        bookingButton = new javax.swing.JLabel();
        priceComparisonButton = new javax.swing.JLabel();
        profile = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        profileButton = new javax.swing.JLabel();
        topPanel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        tabPanel = new javax.swing.JTabbedPane();
        userDashboardPanel = new javax.swing.JPanel();
        flightsPanel = new javax.swing.JPanel();
        myBookingsPanel = new javax.swing.JPanel();
        priceComparisonPanel = new javax.swing.JPanel();
        profilePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sakayLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\UPAir\\src\\main\\java\\assets\\UPAir Logo.png")); // NOI18N
        getContentPane().add(sakayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 50));

        toggleLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\SaKaY\\src\\main\\java\\assets\\ToggleButton.png")); // NOI18N
        toggleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleLabelMouseClicked(evt);
            }
        });
        getContentPane().add(toggleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        searchLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\SaKaY\\src\\main\\java\\assets\\Search  Button.png")); // NOI18N
        searchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchLabelMouseClicked(evt);
            }
        });
        getContentPane().add(searchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, -1, 30));

        welcomeLabel.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        welcomeLabel.setText("Welcome, Juan!");
        getContentPane().add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, -1, -1));

        dividerLabel.setFont(new java.awt.Font("Arial Narrow", 0, 48)); // NOI18N
        dividerLabel.setForeground(new java.awt.Color(63, 164, 251));
        dividerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dividerLabel.setText("|");
        getContentPane().add(dividerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 30, 80));

        sidePanel.setBackground(new java.awt.Color(1, 31, 82));
        sidePanel.setPreferredSize(new java.awt.Dimension(250, 520));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\UPAir\\src\\main\\java\\assets\\Dashboard.png")); // NOI18N
        dashboardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardButtonMouseClicked(evt);
            }
        });
        sidePanel.add(dashboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 240, -1));

        flightsButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\UPAir\\src\\main\\java\\assets\\Flights.png")); // NOI18N
        flightsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flightsButtonMouseClicked(evt);
            }
        });
        sidePanel.add(flightsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 240, -1));

        myBookingsButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\UPAir\\src\\main\\java\\assets\\My Bookings.png")); // NOI18N
        myBookingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myBookingsButtonMouseClicked(evt);
            }
        });
        sidePanel.add(myBookingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 240, -1));

        bookingButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\UPAir\\src\\main\\java\\assets\\Bookings.png")); // NOI18N
        bookingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingButtonMouseClicked(evt);
            }
        });
        sidePanel.add(bookingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 240, -1));

        priceComparisonButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\UPAir\\src\\main\\java\\assets\\Price Comparison.png")); // NOI18N
        priceComparisonButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                priceComparisonButtonMouseClicked(evt);
            }
        });
        sidePanel.add(priceComparisonButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 240, -1));

        profile.setBackground(new java.awt.Color(1, 31, 82));
        profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("User");
        profile.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 30));

        profileButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\UPAir\\src\\main\\java\\assets\\Profile.png")); // NOI18N
        profileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileButtonMouseClicked(evt);
            }
        });
        profile.add(profileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, -1));

        sidePanel.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 130, 50));

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 520));

        topPanel.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\SaKaY\\src\\main\\java\\assets\\Top Bar.png")); // NOI18N
        getContentPane().add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 80));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userDashboardPanel.setBackground(new java.awt.Color(255, 255, 0));
        userDashboardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tabPanel.addTab("tab1", userDashboardPanel);

        flightsPanel.setBackground(new java.awt.Color(204, 0, 0));
        flightsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tabPanel.addTab("tab2", flightsPanel);

        myBookingsPanel.setBackground(new java.awt.Color(0, 204, 0));
        myBookingsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tabPanel.addTab("tab3", myBookingsPanel);

        priceComparisonPanel.setBackground(new java.awt.Color(51, 255, 255));
        priceComparisonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tabPanel.addTab("tab4", priceComparisonPanel);

        profilePanel.setBackground(new java.awt.Color(255, 204, 204));
        tabPanel.addTab("tab5", profilePanel);

        jPanel1.setBackground(new java.awt.Color(255, 0, 255));
        tabPanel.addTab("tab6", jPanel1);

        mainPanel.add(tabPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 900, 560));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 900, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toggleLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleLabelMouseClicked
        // TODO add your handling code here:
        if (isExpanded) {
            animateMenu(false);
        } else {
            animateMenu(true);
        }
    }//GEN-LAST:event_toggleLabelMouseClicked

    private void searchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchLabelMouseClicked

    private void dashboardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardButtonMouseClicked
        // TODO add your handling code here:
        tabPanel.setSelectedIndex(0);
    }//GEN-LAST:event_dashboardButtonMouseClicked

    private void flightsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flightsButtonMouseClicked
        // TODO add your handling code here:
        tabPanel.setSelectedIndex(1);
    }//GEN-LAST:event_flightsButtonMouseClicked

    private void myBookingsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myBookingsButtonMouseClicked
        // TODO add your handling code here:
        tabPanel.setSelectedIndex(3);
    }//GEN-LAST:event_myBookingsButtonMouseClicked

    private void profileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileButtonMouseClicked
        // TODO add your handling code here:
        tabPanel.setSelectedIndex(4);
    }//GEN-LAST:event_profileButtonMouseClicked

    private void bookingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingButtonMouseClicked
        // TODO add your handling code here:
        tabPanel.setSelectedIndex(2);
    }//GEN-LAST:event_bookingButtonMouseClicked

    private void priceComparisonButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priceComparisonButtonMouseClicked
        // TODO add your handling code here:
        tabPanel.setSelectedIndex(5);
    }//GEN-LAST:event_priceComparisonButtonMouseClicked

    private void animateMenu(boolean expand) {
        if (timer != null && timer.isRunning()) {
            return;
        }

        timer = new javax.swing.Timer(0, null);

        timer.addActionListener(e -> {
            if (expand) {
                if (menuWidth < 250) {
                    menuWidth++;
                    sidePanel.setSize(menuWidth, 520);
                } else {
                    isExpanded = true;
                    timer.stop();
                }
            } else {
                if (menuWidth > 0) {
                    menuWidth--;
                    sidePanel.setSize(menuWidth, 520);
                } else {
                    isExpanded = false;
                    timer.stop();
                }
            }
        });

        timer.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassengerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassengerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassengerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassengerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookingButton;
    private javax.swing.JLabel dashboardButton;
    private javax.swing.JLabel dividerLabel;
    private javax.swing.JLabel flightsButton;
    private javax.swing.JPanel flightsPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel myBookingsButton;
    private javax.swing.JPanel myBookingsPanel;
    private javax.swing.JLabel priceComparisonButton;
    private javax.swing.JPanel priceComparisonPanel;
    private javax.swing.JPanel profile;
    private javax.swing.JLabel profileButton;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JLabel sakayLabel;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JLabel toggleLabel;
    private javax.swing.JLabel topPanel;
    private javax.swing.JPanel userDashboardPanel;
    private javax.swing.JLabel username;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}